Blog post why PySpark save mode transactions are better in Delta Lake
delta-io/website pull request #173
Opened 2022-11-01 03:21 UTC by MrPowers

2022-11-02 22:02 UTC, dennyglee requested changes
Great blog - some minor formatting and grammar changes requested in addition to some image swaps

2022-11-02 22:02 UTC, dennyglee commented on src/blog/2022-11-01-pyspark-save-mode-append-overwrite-error/index.mdx
> +Here are the contents of the Delta Lake after the write with save mode set to ignore:
Please add **table**

2022-11-02 22:02 UTC, dennyglee commented on src/blog/2022-11-01-pyspark-save-mode-append-overwrite-error/index.mdx
> +When the save mode is set to ignore, the data in `df2` is not appended and an error is not thrown.
Please code format `ignore`

2022-11-02 22:02 UTC, dennyglee commented on src/blog/2022-11-01-pyspark-save-mode-append-overwrite-error/index.mdx
> +Delta Lake supports versioned data and time travel. It only physically removes files from disk when you run the vacuum command to remove unneeded old files to save your storage cost.
Please code format `vacuum`

2022-11-03 15:38 UTC, MrPowers commented on src/blog/2022-11-01-pyspark-save-mode-append-overwrite-error/index.mdx
> +We’ve confirmed that PySpark will error when writing to an existing Delta Lake if the save mode is set to error.
@dennyglee - good catch, will update to "Delta table" instead of "Delta Lake table" per feedback from @allisonport-db 🤓

2022-11-03 15:41 UTC, MrPowers commented on src/blog/2022-11-01-pyspark-save-mode-append-overwrite-error/index.mdx
> +![](image4.png)
All the images got messed up on the initial commit.  I fixed them in [this commit a couple of days back](https://github.com/delta-io/website/pull/173/commits/bdbc1fa613df1a37b63972770638d7cca38b7943), but I don't think that was ever reflected in the Netlify preview, so you're understandably confused.  We'll see if this latest commit properly triggers a Netlify rebuild (or if there is some caching issue).

2022-11-03 15:47 UTC, MrPowers commented on src/blog/2022-11-01-pyspark-save-mode-append-overwrite-error/index.mdx
> +## Parquet append and overwrite save modes
This is a wonderful suggestion from an SEO perspective!!

2022-11-04 14:30 UTC, dennyglee commented on src/blog/2022-11-01-pyspark-save-mode-append-overwrite-error/index.mdx
> +We’ve confirmed that PySpark will error when writing to an existing Delta Lake if the save mode is set to error.
👍

2022-11-04 14:33 UTC, dennyglee approved these changes
LGTM!

2022-11-04 14:34 UTC, merged