split images and added link to current user-stories
delta-io/website pull request #283
Opened 2023-05-11 12:27 UTC by dev-smart-ui

resolves #278

2023-05-16 23:22 UTC, dennyglee commented
Thanks @dev-smart-ui - this is looking pretty good.  Saying this, could you add some more vertical spacing between the different logos.  The horizontal spacing is quite good but the vertical spacing seems squat.

As well, could you include all of the logos from the original diagram as well as any new ones?  Thanks!

2023-05-17 14:44 UTC, dev-smart-ui commented
Hey @dennyglee ! 
Thanks for your feddback. 

I added more row spacing between the icons. As for quontity of icons I added all of them from the current scheme (included Kubit), but I changed the grid from 6(columns) x 4(rows) to the 5(columns) x 5(rows). In other way we will get only one icons for last row. It looks not well. 

What do you think?

2023-05-17 17:29 UTC, dennyglee requested changes
Two quick changes - thanks!

2023-05-17 17:29 UTC, dennyglee commented on src/components/pages/community/ContributeToDeltaSection/contributors.js
> +export const contributors = [
Could we rename this to `orgContributors` vs `contributors` so we don't confuse between organizations vs. contributors (maintainers).

2023-05-17 17:29 UTC, dennyglee commented on src/components/pages/community/ContributeToDeltaSection/index.jsx
> +    <Grid columns={{ xs: 2, sm: 3, md: 4, lg: 5 }} gutter="lg" rowGutter="xl">
Can we try rowGutter = "xxl"?

2023-05-17 17:29 UTC, dennyglee commented
Thanks @dev-smart-ui  - can we try xxl row gutter just to see if it looks better?  As for the icons - that's fair, just wanted to confirm that I can add another 5 icons :)

2023-05-19 05:03 UTC, dennyglee commented on src/components/pages/community/ContributeToDeltaSection/contributors.js
> +export const contributors = [
thanks!

2023-05-19 05:03 UTC, dennyglee commented on src/components/pages/community/ContributeToDeltaSection/index.jsx
> +    <Grid columns={{ xs: 2, sm: 3, md: 4, lg: 5 }} gutter="lg" rowGutter="xl">
thanks, looks great!

2023-05-19 05:07 UTC, dennyglee approved these changes
awesome, thanks!

2023-05-19 05:07 UTC, dennyglee approved these changes
awesome, thanks!

2023-05-19 05:07 UTC, merged