Remove explicit references to the `connectors` repo
delta-io/website pull request #325
Opened 2023-08-15 17:12 UTC by manuteleco

The [connectors](https://github.com/delta-io/connectors) repository has been recently archived (on Jul 13, 2023). Its contents have been moved into the [delta](https://github.com/delta-io/delta) repository, under `connectors`.

Therefore, the website should not include explicit mentions or calls for contributions to the archived `connectors` repository anymore.

---

Closes #324

2023-08-31 04:16 UTC, dennyglee requested changes

2023-08-31 04:16 UTC, dennyglee commented on src/components/pages/community/ContributeSection/index.jsx
> +            "Delta Lake connectors for Apache Spark™, with Scala/Java and Python APIs, and for non-Spark engines like Hive, Flink, Java, etc.",
Perhaps phrasing it as "Java-based engines like Hive, Flink, PrestoDB, etc."?  WDYT?

2023-09-02 10:01 UTC, manuteleco commented on src/components/pages/community/ContributeSection/index.jsx
> +            "Delta Lake connectors for Apache Spark™, with Scala/Java and Python APIs, and for non-Spark engines like Hive, Flink, Java, etc.",
Definitely better, thanks.

I've changed the phrasing and rebased from `main`.

2023-09-03 20:47 UTC, dennyglee approved these changes
thanks very much @manuteleco  - this is awesome!

2023-09-03 20:47 UTC, merged