Update links to the `connectors` repository
delta-io/website pull request #327
Opened 2023-08-15 17:16 UTC by manuteleco

The [connectors](https://github.com/delta-io/connectors) repository has been recently archived (on Jul 13, 2023). Its contents have been moved into the [delta](https://github.com/delta-io/delta) repository, under `connectors`.

Therefore, any link pointing to the archived repository should be updated to point to the new location instead.

We update links from published blog posts as well, as that's probably the right thing to do.

But we leave untouched any link that refers to an issue, a release, a pull request or a branch, as those should still point to the archived repository. Only links that refer to files or directories within the repository are adjusted.

---

Closes #326

2023-08-15 17:18 UTC, manuteleco commented on src/blog/2023-07-07-delta-lake-transaction-log-protocol/index.mdx
> +- [delta-io/connectors](https://github.com/delta-io/delta/tree/master/connectors)
This case is a bit awkward, in that it names the archived repo (delta-io/connectors) but links to the new location. I wonder whether I should simply delete this item instead. What do you think?

2023-08-31 03:59 UTC, dennyglee commented on src/blog/2023-07-07-delta-lake-transaction-log-protocol/index.mdx
> +- [delta-io/connectors](https://github.com/delta-io/delta/tree/master/connectors)
@manuteleco good point, I think we should just delete it.  Everything looks great.  could you remove it and I'll approve and merge?

2023-08-31 04:02 UTC, dennyglee requested changes
Thanks very much for doing this @manuteleco  - everything looks great!  Per your own call out for the delta connectors link, please update and I'll merge this.  Feel free to tag me as well.  Much appreciated!

2023-09-02 10:02 UTC, manuteleco commented on src/blog/2023-07-07-delta-lake-transaction-log-protocol/index.mdx
> +- [delta-io/connectors](https://github.com/delta-io/delta/tree/master/connectors)
Removed. Thanks.

2023-09-03 19:21 UTC, dennyglee approved these changes
LGTM!

2023-09-03 19:22 UTC, dennyglee commented
Thanks @manuteleco !

2023-09-03 19:22 UTC, merged