Add Delta lake upsert blog
delta-io/website pull request #487
Opened 2024-11-14 14:28 UTC by avriiil

This PR adds a blog about "delta lake upsert"

2024-11-20 00:37 UTC, newfront requested changes
Just the two small typos and this is good to go. :)

2024-11-20 00:37 UTC, newfront commented on src/blog/delta-lake-upsert/index.mdx
> +- **Optimize Table Performance**: Periodically optimize and vacuum yourDelta tables to improve performance and reduce storage costs. Read more in the [Delta Lake Optimize post](https://delta.io/blog/
typo: there is a missing space between `yourDelta`, should be your Delta tables.

2024-11-20 00:37 UTC, newfront commented on src/blog/delta-lake-upsert/index.mdx
> +This took more than 28seconds on an M1 Macbook Pro with 8 cores. That’s quite slow for a single upsert operation.
typo: missing space between 28 and seconds.

2024-11-21 10:55 UTC, avriiil commented
thanks @newfront, this should be good to go now!

2024-11-22 05:33 UTC, newfront approved these changes
This looks good to me. :shipit:

2024-11-22 05:35 UTC, newfront commented
@dennyglee could you give this a +1 and help get this out the door?

2024-12-28 02:11 UTC, merged