Delta 1.2 blog and Updates to main page highlights
delta-io/website pull request #76
Opened 2022-05-03 18:53 UTC by vinijaiswal

- Delta 1.2 blog released
- Featured section updated with latest 4 community engagements.

2022-05-03 19:09 UTC, vinijaiswal commented
Signed-off-by: Vini Jaiswal <vini.js1303@gmail.com>
@dennyglee Can you please review? Thank you!

2022-05-04 01:20 UTC, dennyglee requested changes
Great blog - please update per requested changes - thanks!

2022-05-05 01:13 UTC, dennyglee commented on src/blog/2022-05-05-delta-lake-1-2-released/index.mdx
> +> Visit [Delta Lake](https://github.com/delta-io/delta) to learn more, you can join the Delta Lake community via [Slack](http://dbricks.co/delta-users-slack) and [Google Group](https://groups.google.
Please change the link from dbricks.co/delta-users-slack to go.delta.io/delta-users

2022-05-05 01:14 UTC, dennyglee commented
Thanks @vinijaiswal - there are four issues remaining - could you please address them and we'll get this closed out.  Thanks!

2022-05-05 03:27 UTC, dennyglee requested changes
Could you please undo the `package-lock.json` and validate locally that the original version still works?

2022-05-05 03:27 UTC, dennyglee commented on src/blog/2022-05-05-delta-lake-1-2-released/index.mdx
> +-- Optimizes Delta Lake table
Lines 56 and 57 should be included in the lines 60 and 61.  That is lines 61. should be 
```sql
OPTIMIZE delta_table_name;                -- Optimizes Delta Lake Table
OPTIMIZE delta.`/path/to/delta/table`;    -- Optimizes the path-based Delta Lake table
```

2022-05-05 14:08 UTC, dennyglee requested changes
Please revert the package-lock.json to a previous version of the file - thanks!

2022-05-05 14:08 UTC, dennyglee commented on src/blog/2022-05-05-delta-lake-1-2-released/index.mdx
> +> Visit [Delta Lake](https://github.com/delta-io/delta) to learn more, you can join the Delta Lake community via [Slack](go.delta.io/delta-users) and [Google Group](https://groups.google.com/forum/#!
Please change `go.delta.io/delta-users` to `https://go.delta.io/delta-users`

2022-05-05 17:58 UTC, dennyglee commented on src/blog/2022-05-05-delta-lake-1-2-released/index.mdx
> +> Visit [Delta Lake](https://github.com/delta-io/delta) to learn more, you can join the Delta Lake community via [Slack](go.delta.io/delta-users) and [Google Group](https://groups.google.com/forum/#!
thanks!

2022-05-05 17:59 UTC, dennyglee approved these changes
LGTM!

2022-05-05 17:59 UTC, merged